SELECT 
    a.USER_ID,
    a.NICKNAME,
    SUM(b.PRICE)
        AS TOTAL_SALES
FROM USED_GOODS_USER AS a
JOIN
    USED_GOODS_BOARD AS b
ON 
    b.WRITER_ID = a.USER_ID
WHERE b.STATUS = 'DONE'
GROUP BY a.USER_ID
HAVING
    TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES ASC
    ;