# SELECT 
#     a.ITEM_ID AS ITEM_ID,
#     a.ITEM_NAME AS ITEM_NAME,
#     a.RARITY AS RARITY
# FROM
#     ITEM_INFO AS a
# JOIN
#     ITEM_TREE AS b
# ON
#     a.ITEM_ID = b.PARENT_ITEM_ID AND
#     IS NOT NULL b.PARENT_ITEM_ID
# WHERE
#     a.RARITY = 'RARE';

SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE ITEM_ID IN(
        SELECT ITEM_ID
        FROM ITEM_TREE
        WHERE PARENT_ITEM_ID IN(
            SELECT ITEM_ID
            FROM ITEM_INFO
            WHERE RARITY = 'RARE'
        )
    )
ORDER BY
    ITEM_ID DESC;