-- PRODUCT = ID, CODE, PRICE
-- 10000원 단위 가격대 별 상품 개수 출력
-- PRICE_GROUP, PRODUCTS(개수)
SELECT
    TRUNCATE(PRICE, -4) AS PRICE_GROUP,
    COUNT(*) PRODUCTS
FROM 
    PRODUCT
GROUP BY 
    PRICE_GROUP
ORDER BY PRICE_GROUP ASC
;